import type { Template } from "../types"

export const expressTemplate: Template = {
  id: "express-typescript",
  name: "Express + TypeScript",
  description: "A REST API built with Express and TypeScript",
  category: "Backend",
  language: "TypeScript",
  framework: "Express",
  version: "1.0.0",
  options: [
    {
      id: "packageManager",
      label: "Package Manager",
      type: "select",
      choices: ["npm", "pnpm", "yarn"],
      default: "npm",
    },
    {
      id: "testing",
      label: "Testing",
      type: "checkbox",
      default: false,
    },
  ],
  files: [
    {
      path: "package.json",
      content: `{
  "name": "{{projectName}}",
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "tsx watch src/index.ts",
    "build": "tsc",
    "start": "node dist/index.js"
  },
  "dependencies": {
    "express": "^4.21.0"
  },
  "devDependencies": {
    "@types/express": "^5.0.0",
    "@types/node": "^20",
    "tsx": "^4.19.0",
    "typescript": "^5"
  }
}`,
    },
    {
      path: "tsconfig.json",
      content: `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"]
}`,
    },
    {
      path: "src/index.ts",
      content: `import express from 'express'

const app = express()
const port = process.env.PORT || 3000

app.use(express.json())

app.get('/', (_req, res) => {
  res.json({ message: 'Welcome to {{projectName}}' })
})

app.listen(port, () => {
  console.log(\`Server running at http://localhost:\${port}\`)
})`,
    },
    {
      path: ".gitignore",
      content: `node_modules
dist
*.log
.DS_Store`,
    },
    {
      path: "README.md",
      content: `# {{projectName}}

Express + TypeScript API generated by Catalyst.

## Getting Started

\`\`\`bash
{{packageManager}} install
{{packageManager}} run dev
\`\`\`

The server will start at http://localhost:3000
`,
    },
  ],
}
