import type { Template } from "../types"

export const flaskTemplate: Template = {
  id: "python-flask",
  name: "Python Flask",
  description: "A Python web application using Flask",
  category: "Backend",
  language: "Python",
  framework: "Flask",
  version: "1.0.0",
  options: [
    {
      id: "testing",
      label: "Testing",
      type: "checkbox",
      default: false,
    },
  ],
  files: [
    {
      path: "requirements.txt",
      content: `flask>=3.0.0
`,
    },
    {
      path: "app.py",
      content: `from flask import Flask, jsonify

app = Flask(__name__)


@app.route("/")
def home():
    return jsonify({"message": "Welcome to {{projectName}}"})


if __name__ == "__main__":
    app.run(debug=True)
`,
    },
    {
      path: ".gitignore",
      content: `__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
venv/
.venv/
*.log
.DS_Store`,
    },
    {
      path: "README.md",
      content: `# {{projectName}}

Python Flask application generated by Catalyst.

## Getting Started

\`\`\`bash
python -m venv venv
source venv/bin/activate  # On Windows: venv\\Scripts\\activate
pip install -r requirements.txt
python app.py
\`\`\`

The server will start at http://localhost:5000
`,
    },
  ],
}
