import type { Template } from "../types"

export const nextjsTemplate: Template = {
  id: "nextjs",
  name: "Next.js",
  description: "A full-stack Next.js application with App Router",
  category: "Full-stack",
  language: "TypeScript",
  framework: "Next.js",
  version: "1.0.0",
  options: [
    {
      id: "packageManager",
      label: "Package Manager",
      type: "select",
      choices: ["npm", "pnpm", "yarn"],
      default: "npm",
    },
    {
      id: "styling",
      label: "Styling",
      type: "select",
      choices: ["tailwind", "css-modules", "none"],
      default: "tailwind",
    },
    {
      id: "testing",
      label: "Testing",
      type: "checkbox",
      default: false,
    },
  ],
  files: [
    {
      path: "package.json",
      content: `{
  "name": "{{projectName}}",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "^15.0.0",
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "typescript": "^5"
  }
}`,
    },
    {
      path: "tsconfig.json",
      content: `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}`,
    },
    {
      path: "next.config.ts",
      content: `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;`,
    },
    {
      path: "src/app/layout.tsx",
      content: `export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}`,
    },
    {
      path: "src/app/page.tsx",
      content: `export default function Home() {
  return (
    <main>
      <h1>{{projectName}}</h1>
      <p>Next.js application generated by Catalyst</p>
    </main>
  )
}`,
    },
    {
      path: "src/app/globals.css",
      content: `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: system-ui, -apple-system, sans-serif;
  padding: 2rem;
}

main {
  max-width: 800px;
  margin: 0 auto;
}`,
    },
    {
      path: ".gitignore",
      content: `node_modules
.next
out
build
*.tsbuildinfo
next-env.d.ts
.DS_Store`,
    },
    {
      path: "README.md",
      content: `# {{projectName}}

Next.js application generated by Catalyst.

## Getting Started

\`\`\`bash
{{packageManager}} install
{{packageManager}} run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) to view the application.
`,
    },
  ],
}
