import type { Template } from "../types"

export const reactTemplate: Template = {
  id: "react-typescript",
  name: "React + TypeScript",
  description: "A React application built with TypeScript and Vite",
  category: "Frontend",
  language: "TypeScript",
  framework: "React",
  version: "1.0.0",
  options: [
    {
      id: "packageManager",
      label: "Package Manager",
      type: "select",
      choices: ["npm", "pnpm", "yarn"],
      default: "npm",
    },
    {
      id: "styling",
      label: "Styling",
      type: "select",
      choices: ["tailwind", "css-modules", "none"],
      default: "tailwind",
    },
    {
      id: "testing",
      label: "Testing",
      type: "checkbox",
      default: false,
    },
  ],
  files: [
    {
      path: "package.json",
      content: `{
  "name": "{{projectName}}",
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc -b && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  },
  "devDependencies": {
    "@types/react": "^19.0.0",
    "@types/react-dom": "^19.0.0",
    "@vitejs/plugin-react": "^4.3.4",
    "typescript": "~5.7.0",
    "vite": "^6.0.0"
  }
}`,
    },
    {
      path: "tsconfig.json",
      content: `{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "noUncheckedSideEffectImports": true
  },
  "include": ["src"]
}`,
    },
    {
      path: "vite.config.ts",
      content: `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})`,
    },
    {
      path: "index.html",
      content: `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{projectName}}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`,
    },
    {
      path: "src/main.tsx",
      content: `import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)`,
    },
    {
      path: "src/App.tsx",
      content: `export default function App() {
  return (
    <div className="app">
      <h1>{{projectName}}</h1>
      <p>React + TypeScript application generated by Catalyst</p>
    </div>
  )
}`,
    },
    {
      path: "src/index.css",
      content: `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: system-ui, -apple-system, sans-serif;
}

.app {
  padding: 2rem;
  max-width: 800px;
  margin: 0 auto;
}`,
    },
    {
      path: ".gitignore",
      content: `node_modules
dist
dist-ssr
*.local
.DS_Store`,
    },
    {
      path: "README.md",
      content: `# {{projectName}}

React + TypeScript application generated by Catalyst.

## Getting Started

\`\`\`bash
{{packageManager}} install
{{packageManager}} run dev
\`\`\`

## Scripts

- \`dev\` - Start development server
- \`build\` - Build for production
- \`preview\` - Preview production build
`,
    },
  ],
}
